//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_Languages
    {
        public byte LanguageID { get; set; }
        public string LanguageName { get; set; }
        public string LanguageDescr { get; set; }
    }
}
